apiVersion: extensions/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: segment-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: segment-api
    spec:
      containers:
      - name: segment-api
        image: gerrybaird/customer-segmentation:v7.0
        ports:
        - containerPort: 9099
---
apiVersion: v1
kind: Service
metadata:
  name: segment-api-loadbalancer
  labels:
    run: segment-api
spec:
  selector:
    run: segment-api
  type: LoadBalancer
  ports:
   - protocol: TCP
     port: 9099